# fly.toml app configuration file generated for axum-oauth-sample on 2023-12-03T22:47:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "axum-oauth-sample"
primary_region = "mia"

[build]

[env]
HOST = "0.0.0.0"
PORT = "5000"

[http_service]
internal_port = 5000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
